[package]
name = "bpt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions here:
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.113"
rayon = "1.5"
